(() => {
  "use strict";
  const $ = (s) => document.querySelector(s);
  const els = {container:$("#jobsContainer"), search:$("#searchInput"), country:$("#countryFilter"), category:$("#categoryFilter"), score:$("#scoreFilter"), reset:$("#resetFilters"), summary:$("#resultsSummary"), matchCount:$("#matchCount"), appliedCount:$("#appliedCount"), title:$("#results-title"), eyebrow:$("#viewEyebrow"), toast:$("#toast")};
  const state = {jobs:[], view:"matches", applied:readApplied(), theme:matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"};
  document.documentElement.dataset.theme=state.theme;
  function readApplied(){try{return JSON.parse(localStorage.getItem("euUmbrellaApplied")||"{}")}catch{return {}}}
  function saveApplied(){try{localStorage.setItem("euUmbrellaApplied",JSON.stringify(state.applied))}catch{toast("Tracking could not be saved in this browser.")}}
  function escapeHTML(v=""){const d=document.createElement("div");d.textContent=String(v);return d.innerHTML}
  function toast(message){els.toast.textContent=message;els.toast.classList.add("is-visible");clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove("is-visible"),2600)}
  function options(el,values){[...new Set(values.filter(Boolean))].sort().forEach(v=>el.add(new Option(v,v)))}
  function filtered(){const q=els.search.value.trim().toLowerCase(),country=els.country.value,category=els.category.value,min=Number(els.score.value);return state.jobs.filter(j=>state.view==="applied"?state.applied[j.id]:true).filter(j=>j.matchScore>=min).filter(j=>!country||j.country===country).filter(j=>!category||j.category===category).filter(j=>!q||[j.title,j.company,j.location,j.description,(j.matchedKeywords||[]).join(" ")].join(" ").toLowerCase().includes(q))}
  function empty(){const applied=state.view==="applied";return `<div class="empty-state"><svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M4 7h16v13H4zM8 4h8v3H8z"/><path d="m9 13 2 2 4-5"/></svg><h3>${applied?"No tracked applications yet":"No roles pass these filters"}</h3><p>${applied?"Mark a vacancy as applied and it will appear here with your application notes.":"Try 65+ shortlisted or reset the country and keyword filters."}</p><button class="secondary-button" type="button" data-empty-action>${applied?"Show best matches":"Reset filters"}</button></div>`}
  function card(j){const applied=state.applied[j.id]||{};const scoreClass=j.matchScore>=85?"score-high":j.matchScore>=75?"score-medium":"score-low";const desc=(j.description||"").replace(/Search by Keyword.*?Apply now/i,"").slice(0,360);const warnings=(j.warnings||[]).length?`<p class="warning">Check before applying: ${escapeHTML(j.warnings.join(", "))}</p>`:"";return `<article class="job-card ${j.perfectFit?"is-perfect":""}" data-id="${escapeHTML(j.id)}"><div><div class="job-heading"><div><p class="source-line">${j.perfectFit?"Perfect fit · ":""}${escapeHTML(j.employerType||j.source)}</p><h3>${escapeHTML(j.title)}</h3><p class="company">${escapeHTML(j.company)}</p></div><div class="score ${scoreClass}" aria-label="${j.matchScore} percent fit"><strong>${j.matchScore}</strong><span>fit score</span></div></div><p class="meta"><span>${escapeHTML(j.location||j.country)}</span><span>${escapeHTML(j.category)}</span><span>Attainability ${j.attainabilityScore}</span>${j.datePosted?`<span>${escapeHTML(j.datePosted)}</span>`:""}</p><p class="description">${escapeHTML(desc)}${desc.length>=360?"…":""}</p><p class="match-reason">${escapeHTML(j.matchReason)}</p>${warnings}<div class="job-tags">${(j.matchedKeywords||[]).slice(0,7).map(k=>`<span>${escapeHTML(k)}</span>`).join("")}</div></div><div class="job-action"><a class="apply-button" href="${escapeHTML(j.url)}" target="_blank" rel="noopener noreferrer">Open official listing</a><button class="secondary-button" type="button" data-applied>${applied.status?"Update application":"Mark as applied"}</button>${applied.status?`<label class="application-field"><span>Status</span><select data-status><option>Applied</option><option>Interview</option><option>Offer</option><option>Rejected</option><option>Withdrawn</option></select></label><label class="application-field"><span>Notes</span><textarea data-notes rows="3" placeholder="Date, contact, next step…">${escapeHTML(applied.notes||"")}</textarea></label>`:""}<p class="verify-note">Verify deadline on employer site</p></div></article>`}
  function render(){const jobs=filtered();els.container.innerHTML=jobs.length?jobs.map(card).join(""):empty();els.container.setAttribute("aria-busy","false");els.summary.textContent=`${jobs.length} of ${state.view==="applied"?Object.keys(state.applied).length:state.jobs.length} roles shown · ${els.score.value}+ fit`;els.matchCount.textContent=state.jobs.length;els.appliedCount.textContent=Object.keys(state.applied).length;document.querySelectorAll("[data-status]").forEach(s=>{s.value=state.applied[s.closest(".job-card").dataset.id]?.status||"Applied"})}
  function setView(view){state.view=view;document.querySelectorAll(".view-tab").forEach(b=>{const active=b.dataset.view===view;b.classList.toggle("is-active",active);b.setAttribute("aria-selected",active)});els.title.textContent=view==="applied"?"Applied jobs":"Best matches";els.eyebrow.textContent=view==="applied"?"Application tracker":"Opportunity shortlist";render()}
  function reset(){els.search.value="";els.country.value="";els.category.value="";els.score.value="75";render()}
  [els.search,els.country,els.category,els.score].forEach(el=>el.addEventListener(el.tagName==="INPUT"?"input":"change",render));els.reset.addEventListener("click",reset);
  document.addEventListener("click",e=>{const view=e.target.closest("[data-view]");if(view)setView(view.dataset.view);if(e.target.closest("[data-empty-action]")){state.view==="applied"?setView("matches"):reset()}const button=e.target.closest("[data-applied]");if(button){const id=button.closest(".job-card").dataset.id;if(state.applied[id]){state.applied[id].status=state.applied[id].status||"Applied"}else state.applied[id]={status:"Applied",notes:"",date:new Date().toISOString().slice(0,10)};saveApplied();toast("Application tracker updated.");render()}});
  document.addEventListener("change",e=>{if(e.target.matches("[data-status]")){const id=e.target.closest(".job-card").dataset.id;state.applied[id].status=e.target.value;saveApplied();toast("Status saved.")}});
  document.addEventListener("input",e=>{if(e.target.matches("[data-notes]")){const id=e.target.closest(".job-card").dataset.id;state.applied[id].notes=e.target.value;saveApplied()}});
  $("[data-theme-toggle]").addEventListener("click",()=>{state.theme=state.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=state.theme});
  async function init(){try{const r=await fetch("./jobs.json",{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);const data=await r.json();state.jobs=(data.jobs||[]).sort((a,b)=>Number(b.perfectFit)-Number(a.perfectFit)||b.matchScore-a.matchScore||b.attainabilityScore-a.attainabilityScore);options(els.country,state.jobs.map(j=>j.country));options(els.category,state.jobs.map(j=>j.category));render()}catch(err){els.container.innerHTML=`<div class="empty-state"><h3>Vacancy feed unavailable</h3><p>${escapeHTML(err.message)}. Run the collector or check the GitHub Actions source-health log.</p></div>`;els.summary.textContent="Could not load current vacancies."}}
  init();
})();
